# Generated by Django 5.0.6 on 2024-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('topic', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Product Support', 'Product Support'), ('Sales Inquiry', 'Sales Inquiry')], max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('investment_size', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('agree_terms', models.BooleanField()),
            ],
        ),
    ]
